version: "3.9"

services:
  verificador:
    build: .
    container_name: verificador-processos
    ports:
      - "8000:8000"   # FastAPI local
      - "8501:8501"   # Streamlit local
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-4o
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - API_URL=http://localhost:8000
    volumes:
      - .:/app   # monta o código local dentro do container (bom p/ desenvolvimento)
